import "./globals.css";
import { Poppins } from "next/font/google";
import { Footer, Navbar } from "@/components/componentsindex";
import { AppKitProvider } from "@/context/appkit";
import { NFTMarketplaceProvider } from "@/context/NFTMarketplaceContext";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "NFT MARKETPLACE",
  description: "Generated by Next.js 15",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <AppKitProvider>
          <NFTMarketplaceProvider>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </NFTMarketplaceProvider>
        </AppKitProvider>
      </body>
    </html>
  );
}
